pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("python-app:latest")
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    docker.image("python-app:latest").run()
                }
            }
        }
    }
}
